//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bilisimprojesi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ayarlar
    {
        public int id { get; set; }
        public Nullable<bool> hizliislem { get; set; }
        public Nullable<bool> tarihsaatgosterimi { get; set; }
        public Nullable<bool> sifresorma { get; set; }
        public string k_adi { get; set; }
        public string sifre { get; set; }
        public string isletme_adi { get; set; }
    }
}
