//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bilisimprojesi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class carihareket
    {
        public int ch_id { get; set; }
        public string ch_urun { get; set; }
        public Nullable<decimal> ch_tutar { get; set; }
        public Nullable<System.DateTime> ch_tarih { get; set; }
        public string ch_aciklama { get; set; }
        public Nullable<int> m_id { get; set; }
        public Nullable<bool> ch_harekettipi { get; set; }
    
        public virtual musteriler musteriler { get; set; }
    }
}
