//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bilisimprojesi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteriler
    {
        public musteriler()
        {
            this.cariharekets = new HashSet<carihareket>();
        }
    
        public int m_id { get; set; }
        public string m_ad { get; set; }
        public string m_soyad { get; set; }
        public string m_telefon { get; set; }
        public string m_ceptel { get; set; }
        public string m_mail { get; set; }
        public string m_tc { get; set; }
        public string m_adres { get; set; }
        public string m_aciklama { get; set; }
    
        public virtual ICollection<carihareket> cariharekets { get; set; }
    }
}
